name: context-example
on: ["push"]
jobs: 
  sm-context:
    runs-on: ubuntu-latest
    steps:
      - name: "sm step"
        run: |
            echo "ACTION: $MY_ACTION"
            echo "ACTOR: $MY_ACTOR"
        env: 
            MY_ACTION: ${{ github.action }}
            MY_ACTOR: ${{ github.actor }}